### ISSUE TITLE
overriding the MenuItem entity

### ISSUE THREAD

**Issue by lucsoulier** [monsieurbiz/SyliusMenuPlugin#43]
Hi

How customize the menu_item Model ?
The override doesn’t work.

_sylius.yaml
```
sylius_resource:
    resources:      
        monsieurbiz_menu.menu_item:
            classes:
                model: App\Entity\MonsieurBiz\SyliusMenuPlugin\MenuItem

```
Console
` php bin/console debug:container --parameter  monsieurbiz_menu.model.menu_item.class`
 monsieurbiz_menu.model.menu_item.class   MonsieurBiz\SyliusMenuPlugin\Entity\MenuItem
